name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}

          user: Manvendra2223
          template: classic
          base: header, repositories, activity

          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_colors: github
          plugin_languages_priority: python,python,python,jupyter notebook,java,c++

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14

          config_timezone: Asia/Kolkata
          config_animations: yes
