name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"   # daily at 12:00 AM UTC
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Manvendra2223
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit snake to main branch
        uses: EndBug/add-and-commit@v9
        with:
          branch: main
          add: "output"
          message: "Update contribution snake"





